disabled = false
languageCode = 'en-US'
languageName = 'English'
title = 'SIAM DC-Maryland-Virginia 2025' # This will go in the Header as well
copyright = """Designed with [Hugo](https://gohugo.io/) ðŸŽ¨ \n
 Licensed under [MIT license](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md) ðŸ“„""" # Please leave this here to give me and the tools i used some credit for the work, or BuyMeACoffee and change or remove the copyrightlink below :)
contentDir = "content/en"


# Change single params to "false" to remove from rendering
[params]
  subtitle = "Conference on Applied Mathematics" # This goes in the header and in the site title
  # PAGES
  [params.homepage]
    # Notice that SEO meta tags (what appears in google search results) can be set
    # in individual pages frontmatters `/content/<page>`
    ###
    preTitle = 'About Us'
    title = "SIAM-DMV-2025"
    # You can use some markdown safely here as long as you don't include line breaks
    intro= """
### 
___

**Through a collaborative effort involving several institutions' SIAM Student Chapters, including JHU, UMBC, GWU, GMU, Georgetown, UMD College Park, we aim to bring together students and faculty from the DMV area working on all types of mathematics research.**

The aim of this joint meeting among these neighboring institutions and SIAM student chapters presents an exceptional opportunity to bring together math researchers at all levels to learn from peers, share ideas and foster new collaborations. Please join us for poster sessions, research talks, and keynote speakers from distinguished faculty with research expertise spanning machine and statistical learning, numerical methods, mathematical biology, and more.

Look at what this theme is capable to do on the features page, and see a beautiful contacts page example below.
        """
    mainButton = "Schedule"
    mainButtonRef = "services" # Just write the name or slug of the page here
    secondButton = "Registration"
    secondButtonRef = "Registration" # Just write the name or slug of the page here
  # For the blog feed section (visible only if posts are rendered)
    blogTitle = "Organizers"
    blogButton= "More"

[params.office]
  title = "Location"
 description = "This page can be easily customized by adding a google maps link to get directions towards your activity location."
 buttonText = "Get directions" 
 buttonLink = "https://maps.app.goo.gl/8vgTXYk6Q6k7eM7U6" # google maps "share" link here (for button)
 mapLink = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJH0vAqN8EyIkR9NCwaMzXwTg&key=AIzaSyDy0NpkxUq6yapNLVGRsOULcXV9NTV_jwg" # google maps "embed" link here

[params.contacts]
  title = "Get in touch!"
  formCallToAction = "This is a \"contact us\" example page, you can receive form responses on FormSpree."
  socialCallToAction = "You can add your own social media links below!" # These are the same as in [params.social]
  [params.contacts.form]
    formspreeLink = "https://yourformspreelink.com" #subscribe to formspree and add the link for the form here
    firstname = "Firstname*"
    lastname = "Lastname*"
    email = "E-mail*"
    phone = "Phone Number*"
    Inquiry = "Inquiry*"
    checkbox = "I accept that my data will be processed in accordance with the law*"
    submitBtn = "Submit"


[params.services]
  title = "Schedule"
  description = """
  8:30am - 9:30am: Morning Breakfast
  
  9:30am - 10:30am: Poster Session 1  

  10:30am - 10:45am: Refreshment Break  

  11:00am - 12:00pm: Poster Session 2  
  
  12:00pm - 1:00pm: Lunch  
  
  1:00pm - 6:00pm: Keynote Speakers & Selected Student Presentations  
  """

  [params.services.list]
    # You can add as much params.services.list.<N> as you like
    [params.services.list.0]
      title= "Primary Talks"
      description= "The theme is fully responsive and shows perfectly on every screen size."
    [params.services.list.01]
      title = "Posters"
      description= "Hide and show some elements easily from the config file."
    [params.services.list.02]
      title = "TBD"
      description= "The default content language is english (it can be changed), but you can add as many languages as you want very easily, the theme includes an italian language example and a dropdown menÃ¹ for easily switching between languages. Permalinks can be localized in each language (eg. you can have `/contacts` for english and `/contatti` for italian)."

[params.socials]
  enabled = false # enables/disables the whole social section in the footer
  callToAction= "Get connected with us on social networks >"
      [[params.socials.link]]
        name = "github"
        link = "https://github.com/ololiuhqui/magnolia-free-hugo-theme"
      [[params.socials.link]]
        name = "linkedin"
        link = ""
      [[params.socials.link]]
        name = "whatsapp"
        link = ""
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.schedules] # Time schedules (eg. your office openming hours)
  enabledFooter = false # This will add the schedules on the footer too
  enabledContacts = false # This will add the schedule to the contact page
  title = "Schedule details" # For contacts page only
  [params.schedules.days]
  # Use something like "Monday: 9-13" for each day
  # if left empty it is disabled (default)
    day1 = "Monday: 9am â€“ 7pm"
    day2 = "Tuesday: 9am â€“ 7pm"
    day3 = "Wednesday: 9am â€“ 7pm"
    day4 = "Thursday: 9am â€“ 7pm"
    day5 = "Friday: 9am â€“ 7pm"
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = "Johns Hopkins University Homewood campus"
  # extraDescription2 = "VAT No. 0000000000"
  [params.footer.navigate]
  heading = "Navigate"   
  [params.footer.contacts]
  enabled = false # enables/disables the whole contacts section in footer
  heading = "Contact"
  address = "Shriver Hall, 3400 N Charles St Ste 14, Baltimore, MD 21218"
  mail = "dundermifflin@fakemail.com"
  mail2 = "dundermifflinorders@fakemail.com"
  phone = "+00 0000000"
  
[params.notfound]
  title = "404, page not found" # text for 404 page

[params.single] # for posts pages (visible only if posts are rendered)
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
# PageRef should refer to the "translationKey" in `/content/<page>` frontmatter, names can be changed freely
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Schedule"
  pageRef = "pages/services"
  weight = 2
  [[menus.main]]
  name = "Location"
  pageRef = "pages/office"
  weight = 4
  [[menus.main]]
  name = "Speakers"
  pageRef = "pages/contacts"
  weight = 3